apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: user-service-deployment
spec:
   replicas: 2
   revisionHistoryLimit: 100
   template:
      metadata:
         labels:
            app: user-service
      spec:
         containers:
         - name: product-service-app
           image: gcr.io/practice-239003/user-service
           ports:
           - name: spring-port
             containerPort: 8080
           livenessProbe:
            httpGet:
                path: /user/product
                port: spring-boot-port
            initialDelaySeconds: 15
            timeoutSeconds: 30